# -*- coding: utf-8 -*-
"""Practise Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gU0QfTQXTP4PNfZFQm4ZEetLSFbmm8kH
"""

import random

def number_guessing_game():
    num = random.randint(1,7)
    tries = 7

    print("Guess a number between 1 and 7")

    while tries > 0:
        guess = int(input("Your guess: "))

        if guess == num:
            print("You win!")
            return
        elif guess < num:
            print("Too low!")
        else:
            print("Too high!")

        tries -= 1
        print(f"Tries left: {tries}")

    print(f"Game over! The number was {num}.")

number_guessing_game()